version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Run Tests
          command: npm test
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
   heroku_deploy:
    jobs:
      - heroku/deploy-via-git
