version: 2.1
orbs:
  react: thefrontside/react@0.2.0
  heroku: circleci/heroku@0.0.10
workflows:
   heroku_deploy:
    jobs:
      - react/install
      - react/test:
          requires:
            - react/install
      - heroku/deploy-via-git:
            requires:
                - react/test
